### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Tuvqlu** [ZulfahmiFjr/SoulWell#5]
Can you make is so console has permission to give souls to a player? Thanks

**Comment by ZulfahmiFjr** [comment]
> Can you make is so console has permission to give souls to a player? Thanks

asap.

**Comment by ZulfahmiFjr** [comment]
> Can you make is so console has permission to give souls to a player? Thanks

done bruhhh...

**Comment by Tuvqlu** [comment]
Thanks :d
